### ISSUE TITLE
[1] Backend framework selection

### ISSUE THREAD

**Issue by jrojewski** [lzdunowski/peak#3]
Evaluate pros and cons of Flask vs Django based on project complexity and features.

Deliverable: Decision on chosen backend framework (e.g., Flask chosen).

//lz: imho coin flip django vs flask

**Comment by jrojewski** [comment]
https://www.codecademy.com/resources/blog/flask-vs-django/

Overall Flask is preferred for smaller projects but Django is quicker to use and has bigger community and it's easier to find answers when you occur the problems.

In my opinion we should choose Django because it may pay off in the future with next projects.

@lzdunowski Tell me what you think, please

**Comment by lzdunowski** [comment]
Django seems fine. Let's use it.
